### ISSUE TITLE
Support CORS headers

### ISSUE THREAD

**Issue by blurpy** [QuantAsylum/QA401H#4]
I've started making a simple web interface on top of this API, but the browser complains about missing CORS headers and refuses to connect:

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:9401/Status/Version. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).`

More details here: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSMissingAllowOrigin

Would it be possible to add the necessary headers to support my use case? Either by default or as an option?

If you want to test the web interface you can find it here: https://github.com/blurpy/qa401w

**Comment by QuantAsylum** [comment]
Hi Blurpy this looks awesome I will definitely give a try. I don't understand why this would fail. The origins are the same, just the paths differ. Or is the fact that there's NO CORS header is the problem? If the header was

```Access-Control-Allow-Origin: http://localhost```

Would that suffice?

**Comment by blurpy** [comment]
Thanks!

The problem is that the CORS headers are missing, as we can see with curl:

```
$ curl -v http://localhost:9401/Status/Version
*   Trying 127.0.0.1:9401...
* Connected to localhost (127.0.0.1) port 9401 (#0)
> GET /Status/Version HTTP/1.1
> Host: localhost:9401
> User-Agent: curl/7.72.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: Microsoft-NetCore/2.0
< Date: Mon, 19 Oct 2020 06:10:21 GMT
< Content-Length: 36
< 
* Connection #0 to host localhost left intact
{ "SessionId":"0", "Value":"0.995" }
```

Trying with a CORS bypass proxy it looks like this:

```
$ curl -v http://localhost:8080/http://localhost:9401/Status/Version
*   Trying ::1:8080...
* Connected to localhost (::1) port 8080 (#0)
> GET /http://localhost:9401/Status/Version HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.72.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Access-Control-Allow-Origin: *
< Vary: Origin
< Date: Mon, 19 Oct 2020 06:11:13 GMT
< Content-Length: 37
< Content-Type: text/plain; charset=utf-8
< 
* Connection #0 to host localhost left intact
{ "SessionId":"0", "Value":"0.995" }
```

In this case the proxy adds the header `Access-Control-Allow-Origin: *`.

I tried `Access-Control-Allow-Origin: http://localhost` with 2 cases. One with opening index.html directly in the browser and one using a basic web server on http://localhost:63342/. And both of them failed to load with this message:

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:8080/http://localhost:9401/Status/Version. (Reason: CORS header ‘Access-Control-Allow-Origin’ does not match ‘http://localhost’).`

It seems the browser is very strict about this, so a generic localhost value is not enough.

When making a request the browser sets a header called `Origin`, and it looks like it must match what the server returns for the browser to accept the response.

Example:

1. Opening index.html in the browser directly
Browser sets request header `Origin: null`
The response is accepted if either of these 2 alternatives are returned:

```
Access-Control-Allow-Origin: null
Access-Control-Allow-Origin: *
```

2. Running a webserver at http://localhost:63342 to serve index.html
Browser sets request header `Origin: http://localhost:63342`
The response is accepted if either of these 2 alternatives are returned:

```
Access-Control-Allow-Origin: http://localhost:63342
Access-Control-Allow-Origin: *
```

Some ways to handle this could be:

1. Return `Access-Control-Allow-Origin` with value set the same as `Origin` from the browser
2. Return `Access-Control-Allow-Origin: *`
3. Make the value configurable

**Comment by QuantAsylum** [comment]
Please try [0.996](https://github.com/QuantAsylum/QA401H/releases/tag/0.996) and see if the headers are as needed (option 2 you presented from above was used). I took your qa401w-main zip, changed the basepath in qa401.js to "http://localhost:9401" and was able to get data!

**Comment by QuantAsylum** [comment]
BTW, the responsiveness of your app is quite good and shows the viability of REST for test and measurement.

**Comment by blurpy** [comment]
> BTW, the responsiveness of your app is quite good and shows the viability of REST for test and measurement.

That's cool! I haven't tried the Windows app so I have no point of reference. I was curious how it would stack up.

> Please try 0.996 and see if the headers are as needed (option 2 you presented from above was used). I took your qa401w-main zip, changed the basepath in qa401.js to "http://localhost:9401" and was able to get data!

Thanks! It works for GET requests, but when I try to change settings I get lots of errors. 
Looks like it's preflight requests being sent: https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request

Request:
```
OPTIONS /Settings/BufferSize/32768 HTTP/1.1
Host: localhost:9401
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Access-Control-Request-Method: PUT
Origin: null
DNT: 1
Connection: keep-alive
```

Response:

```
HTTP/1.1 400 Exception encountered: Object reference not set to an instance of an object.
Server: Microsoft-NetCore/2.0
Date: Mon, 19 Oct 2020 17:21:23 GMT
Connection: close
Transfer-Encoding: chunked
```

I'm not sending any OPTIONS requests, but the browser seems to do so automatically when using anything other than GET in a CORS context it seems. 

Sorry, I wasn't aware you had to implement OPTIONS requests to get CORS to work for PUT/POST. Hope that's not too much trouble for you.

**Comment by QuantAsylum** [comment]
Ahhh, OK, I get it: It comes as an OPTION request but the real request is in ```Access-Control-Request-Method: PUT```

Here's another try at this. I added a button to just let me try one request at a time. Be aware that once you start an acquisition that everything will block until it's done. And if you are in an acquisition and try to change a setting, then an exception will occur that should result in a bad request return type . I notice you send a flood of puts, which is good--that needs to be made to work on the server side. But I see sometimes the server seems to be getting out of sync with itself. 

What I'm seeing with 0.9961 (signed and attached to this message) is below and it seems to mostly work with your app in chrome. Probably the response content length should be zero and content type should be empty. But please let me know what you think as I yield your expertise here.

```
>>REQUEST<<
Request URL: http://localhost:9401/Settings/Input/Max/6
Request Method: OPTIONS
Status Code: 200 OK
Remote Address: [::1]:9401
Referrer Policy: strict-origin-when-cross-origin

>>RESPONSE<<
HTTP/1.1 200 OK
Content-Length: 19
Content-Type: application/json
Server: Microsoft-HTTPAPI/2.0
Access-Control-Allow-Headers: Content-Type, Accept, X-Requested-With
Access-Control-Allow-Methods: GET, POST, PUT
Access-Control-Max-Age: 86400
Access-Control-Allow-Origin: *

>>REQUEST<<
OPTIONS /Settings/Input/Max/6 HTTP/1.1
Host: localhost:9401
Connection: keep-alive
Accept: */*
Access-Control-Request-Method: PUT
Origin: null
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36
Sec-Fetch-Mode: cors
Sec-Fetch-Site: cross-site
Sec-Fetch-Dest: empty
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
```
[QA401H_0.9961.zip](https://github.com/QuantAsylum/QA401H/files/5406062/QA401H_0.9961.zip)

**Comment by blurpy** [comment]
Thanks for the help with troubleshooting this!

> Be aware that once you start an acquisition that everything will block until it's done. And if you are in an acquisition and try to change a setting, then an exception will occur that should result in a bad request return type

That's good to know. Maybe I should disable the button to change settings while it's acquiring.

>  I see sometimes the server seems to be getting out of sync with itself.

I've noticed that myself. Look at this screenshot:

![qa401-strange-freq](https://user-images.githubusercontent.com/186016/96548034-75cddd00-12ad-11eb-9e48-b9d630f68507.png)

The signal is very low. It's connected with a loopback connection from output to input, so no DUT. The settings on the right are what's currently set, and applying again or changing it has no effect. Neither does restarting the api. To fix it I have to unplug the QA401 and replug it. Was wondering if it was a hardware fault, but it's probably just some state out of sync right?

>  It comes as an OPTION request but the real request is in Access-Control-Request-Method: PUT

We are getting there I think, but the OPTIONS request is only a "preflight" request, so the real request will come right afterwards as a proper PUT.

I tried this OPTIONS request:

```
$ curl -v -H "Access-Control-Request-Method: PUT" -X OPTIONS http://localhost:9401/Settings/Input/Max/6
*   Trying ::1:9401...
* Connected to localhost (::1) port 9401 (#0)
> OPTIONS /Settings/Input/Max/6 HTTP/1.1
> Host: localhost:9401
> User-Agent: curl/7.72.0
> Accept: */*
> Access-Control-Request-Method: PUT
> 
< HTTP/1.1 200 OK
< Access-Control-Allow-Headers: Content-Type, Accept, X-Requested-With
< Access-Control-Allow-Methods: GET, POST, PUT
< Access-Control-Max-Age: 86400
< Access-Control-Allow-Origin: *
< Content-Type: application/json
< Server: Microsoft-NetCore/2.0
< Date: Tue, 20 Oct 2020 05:47:16 GMT
< Content-Length: 19
< 
* Connection #0 to host localhost left intact
{ "SessionId":"0" }
```

And I could hear the relay click on the QA401. So that means the api executed the request, which I believe it should not have done. I think at this point the api should do the following:

1. Don't change any state
2. Set the headers as you did
3. Return with empty response content, 0 as content-length, and status "204 No Content"

Shortly after the browser will make the real PUT request. The api should behave as it currently does, executing the request and setting the "Access-Control-Allow-Origin: *" header.

Here is an example of how it looks in the browser from 1 click of the "set" button:

![Screenshot_20201020_074340](https://user-images.githubusercontent.com/186016/96549278-926b1480-12af-11eb-88fa-cab7dbeb6b39.png)

The OPTIONS request looks like this:

```
OPTIONS /Settings/SampleRate/48000 HTTP/1.1
Host: localhost:9401
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Access-Control-Request-Method: PUT
Referer: http://localhost:63342/qa401w/index.html?_ijt=p3giuae3uisfand10i8crtq4sd
Origin: http://localhost:63342
DNT: 1
Connection: keep-alive
```

It's asking the api if it's allowed to execute a PUT request from the specified origin.
The api accepts GET, POST, PUT and all origins:

```
HTTP/1.1 200 OK
Access-Control-Allow-Headers: Content-Type, Accept, X-Requested-With
Access-Control-Allow-Methods: GET, POST, PUT
Access-Control-Max-Age: 86400
Access-Control-Allow-Origin: *
Content-Type: application/json
Server: Microsoft-NetCore/2.0
Date: Tue, 20 Oct 2020 06:00:09 GMT
Content-Length: 19
```

Since preflight approves, the browser sends the real PUT request:

```
PUT /Settings/SampleRate/48000 HTTP/1.1
Host: localhost:9401
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Origin: http://localhost:63342
DNT: 1
Connection: keep-alive
Referer: http://localhost:63342/qa401w/index.html?_ijt=p3giuae3uisfand10i8crtq4sd
Content-Length: 0
```

It seems to cache the result of the OPTIONS requests for some time, so next time I save settings it looks like this, with only some OPTIONS requests firing:

![Screenshot_20201020_081258](https://user-images.githubusercontent.com/186016/96551267-4bcae980-12b2-11eb-9f3c-66d90681f855.png)

Since one of the OPTIONS requests failed, the following PUT request was "blocked" from executing by the browser. Saving again we can see it refreshing the OPTIONS for that url:

![Screenshot_20201020_074655](https://user-images.githubusercontent.com/186016/96549430-c21a1c80-12af-11eb-9c28-7588d1dc1345.png)

I hope this helps!

**Comment by QuantAsylum** [comment]
Ahhh, OK, I didn't understand that about OPTIONS thanks for the added detail it was very helpful. I think it's working now, I ran your app for 15 mins on 2K FFT size no leaks no errors. 

If the server throws an exception, the log will now show more detail on that (via inner exception) which should help. Initially, with all requests happening in order, it was easy to see what caused the exception. But with all requests coming over at once, it's harder to figure out which request was the offender hence the change.

Thanks very much for making this stronger and please report any oddities. 

Just to tidy up on other issues reported on forum:

1. Linux setup refinements: To be put on WIKI. 
2. API on Graph/Frequency/AWeighting: Corrected in docs
3. GET /Data/Freq doc issue: Corrected in docs
4. Kaiser Windows type: Removed from API.
5. Fixed tone: Not possible at this time but it will be when QA401H moves into next-gen GUI app


[QA401H_0.9963.zip](https://github.com/QuantAsylum/QA401H/files/5410928/QA401H_0.9963.zip)

**Comment by blurpy** [comment]
I only had a few minutes of testing now before I have to quit for tonight, but it looks like it's working. Great work!
I will continue testing tomorrow.

Great to see the improvements in the docs as well.

What do you think about my last question from the forum about the frequency response graph?

**Comment by blurpy** [comment]
I'm wondering about the handling of amplitude on the audio generator. The api lets me set a value up to 6 dBV.

This is the result (with loopback):

![6db-amplitude-weird-crop](https://user-images.githubusercontent.com/186016/96734622-06461380-13bb-11eb-9124-fa2acc38bcdd.png)

That doesn't look right.

The waveform looks like this:

![6db-amplitude-weird-time-crop](https://user-images.githubusercontent.com/186016/96734640-0ba35e00-13bb-11eb-8510-8ec4ab74db00.png)

I see from the specs:

Output Full Scale: Single Ended: 5.5 dBV = 5.3 VPP = 1.88 VRMS

The attenuator is on, but in any case it should handle 2Vrms even if it was off. So I'm guessing the output is on overdrive here, and not the input being overloaded? It looks fine if I set the amplitude to 5.5.

Should the api only accept a max value of 5.5 perhaps? Or is my device not handling it correctly? Or maybe the api is handling the input wrong?

Also notice that sending 7 to the api makes it crash (core dump and quit):

```
---
Time 16:19:09.458
PUT     Request:http://localhost:9401/Settings/AudioGen/Gen1/On/1000/7
Amplitude must be >= -120 and < 6
Unhandled exception. System.ArgumentException: Specified value has invalid Control characters. (Parameter 'name')
   at System.Net.HttpListenerResponse.set_StatusDescription(String value)
   at (Object)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
Aborted (core dumped)
```

**Comment by QuantAsylum** [comment]
Noted, thanks, is fixed for next release. 

The maximum output is 5.8 dBV on the gui app, and is now the same for QA401H. When the 6.0 value was specified, it was causing a wrap that you see in the time series. 

Also, the newly added exception message had a bad character (CRLF) that is not allowed by RFC2616. So now you should see a more concise and helpful message in the log instead of exit ;) 

![image](https://user-images.githubusercontent.com/27789827/96752374-396cb080-1383-11eb-96fb-98d7f33735f9.png)

Thanks very much for reporting

**Comment by QuantAsylum** [comment]
> What do you think about my last question from the forum about the frequency response graph?

Unfortunately, those items (spectrum and fixed tone) will have to wait. They will first be solved for the universal gui app.

**Comment by blurpy** [comment]
> Noted, thanks, is fixed for next release.
> The maximum output is 5.8 dBV on the gui app, and is now the same for QA401H. When the 6.0 value was specified, it was causing a wrap that you see in the time series.

Great! I changed the max value to 5.8 in my app.

> Unfortunately, those items (spectrum and fixed tone) will have to wait. They will first be solved for the universal gui app.

OK, no problem.

**Comment by blurpy** [comment]
I have a couple more questions.

I had to append +20dB to the frequency data before display in the chart if the attenuator is on, at least to make it match the png generated by the api.

Do I need to modify any of the other data before display when the attenuator is on to make it match the Windows app?

And about the time data, the voltage seems a little bit off compared to the RMS numbers: 

![time-voltage-0dbv-crop](https://user-images.githubusercontent.com/186016/96900683-a6bb3700-1492-11eb-8603-970c3a2d43a6.png)

Voltage peak to peak in the time data is ~2.6, but is expected to be ~2.8 based on the reported RMS from the api.

The scope measurements match the RMS from the api:

![SDS00025](https://user-images.githubusercontent.com/186016/96902037-4dec9e00-1494-11eb-98cd-7ba0ba5eb376.png)

Could it be that the api compensates for some internal signal loss for the RMS calculation, but not when returning the raw time data?

**Comment by QuantAsylum** [comment]
I think that is correct on the 20 dB adder needed for display. I'll check the amplitude part on Monday and report back.

**Comment by blurpy** [comment]
Thanks!

BTW, the improvements to CORS support in the latest development version has been working perfectly for me so far!

**Comment by QuantAsylum** [comment]
Glad it's working, thanks for reporting! The amplitude seems correct to me. Can you please use a trusted DVM to check instead of a scope? For a 0 dBV signal measured using QA401H (256K FFT so there are 5 seconds to lock onto) OR with QAAnalyzer, the result is the same.

**Comment by blurpy** [comment]
I made a new measurement using a Brymen BM869s with the QA401H set to 0 dBV and 256k FFT.
The DMM measured 0.9985V as the max RMS value, starting at 0.9960V.

This is pretty close to the reported RMS from QA401H (0.989V) and the scope (0.991V).

The voltage peak for the different measurements would be:

* 0.9985 Vrms = 1.4123 Vp
* 0.989 Vrms = 1.3988 Vp
* 0.991 Vrms = 1.4016 Vp

I added some debug output during the measurement and found the min and max peaks from the time data:

* Max: 1.2956912630869502 Vp
* Min: -1.2865017670423267 Vp

I can't get the values from the time data to match what I would expected based on the measured RMS from scope, DMM, or QA401H. But maybe I'm misunderstanding the data somehow?

**Comment by QuantAsylum** [comment]
Let me check on the time data. I don't think you are misunderstanding, I think the time data undergoes a scaling before it gets turned into mime.

**Comment by QuantAsylum** [comment]
Adjusted for [0.998](https://github.com/QuantAsylum/QA401H/releases/tag/0.998). I think the QA401 is likely giving the truer value--most DVMs are very good at 60 Hz, but their response is down a bit at 1 kHz. For example, my Fluke 175 reports 0.997 Vrms at 60 Hz fixed 0 dBV tone, but at 1 kHz it reports 0.985 Vrms (about 1% low). And at 10 kHz it reports 0.529 Vrms. 

The change for 0.998 is that the time series is multiplied about 1.08X before being converted to mime and sent back. So, if you are doing math on the time series, the time series you pull across  (which is internally represented in dBFS) should now be in dBV. Please confirm you see the same at your convenience!

**Comment by QuantAsylum** [comment]
Just checked with version 0.998 and your app is showing 0.990Vrms, which is correct. Your default app still wants to see the proxy, though. 

![image](https://user-images.githubusercontent.com/27789827/98298491-f279e000-1f6a-11eb-8b9a-57da4e2ee094.png)

**Comment by blurpy** [comment]
> The change for 0.998 is that the time series is multiplied about 1.08X before being converted to mime and sent back. So, if you are doing math on the time series, the time series you pull across (which is internally represented in dBFS) should now be in dBV. Please confirm you see the same at your convenience!

![time-voltage-0dbv-v0 998-crop](https://user-images.githubusercontent.com/186016/98395001-df930880-205b-11eb-8b76-536684344973.png)

Time series now has voltage peeks at about 1.4V, which is what I would expect, so nice improvement!

> Just checked with version 0.998 and your app is showing 0.990Vrms, which is correct. 

Excellent!

> Your default app still wants to see the proxy, though.

Thanks for the reminder. I have pushed an update now, removing any notes about having to use a proxy.
Don't hesitate to let me know if you see anything else in my app that should be changed.

I also see that the exception handing was improved.
At this point I think everything I've reported has been fixed. Thank you for taking the time! You can close the issue any time.

**Comment by blurpy** [comment]
Hi again! I've noticed a couple of more related issues.

1. When sending parameters that don't pass validation, the CORS headers are missing in the response:

![cors-missing-on-error](https://user-images.githubusercontent.com/186016/100903633-6c4bad80-34c6-11eb-91f1-eb6303345312.png)

As you can see, I get the status code 400 and a descriptive message in the developer console. I would like to show that message to the user to make it easier to understand errors that may happen.

Unfortunately the browser blocks access to the response, as you can see by the message right below, complaining about the missing CORS header. I'm printing the entire XMLHttpRequest below that, and the response has been cleared, and the status code is 0.

Is it possible to include the CORS headers even when validation fails?

2. The api core dumps if I forget to send a content-length header:

```
$ curl -v -X PUT http://localhost:9401/Settings/AudioGen/Gen2/Off/4500/-400
*   Trying ::1:9401...
* Connected to localhost (::1) port 9401 (#0)
> PUT /Settings/AudioGen/Gen2/Off/4500/-400 HTTP/1.1
> Host: localhost:9401
> User-Agent: curl/7.73.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 411 Length Required
< Content-Type: text/html
< Server: Microsoft-NetCore/2.0
< Date: Wed, 02 Dec 2020 16:53:51 GMT
< Content-Length: 24
< Connection: close
< 
* Closing connection 0
<h1>Length Required</h1>
```

It completes the response to the client, then this happens on the server:

```
---
Time 17:53:51.354
PUT     Request:http://localhost:9401/Settings/AudioGen/Gen2/Off/4500/-400
Amplitude must be >= -120 and <= 5.8
Unhandled exception. System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.HttpListenerResponse'.
   at System.Net.HttpListenerResponse.CheckDisposed()
   at System.Net.HttpListenerResponse.set_StatusCode(Int32 value)
   at ..(Object )
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
Aborted (core dumped)
```

**Comment by QuantAsylum** [comment]
If I send 

```curl -v -X PUT http://localhost:9401/Settings/AudioGen/Gen2/Off/4500/-400```

the server never has a chance to process it. The log output is unchanged. It looks like it's all the decision making is decided in the HttpListenerContext.

If I send 

```curl -d "" -v -X PUT http://localhost:9401/Settings/AudioGen/Gen2/Off/4500/-400```

![image](https://user-images.githubusercontent.com/27789827/101666185-bff85280-3a02-11eb-90c7-acb99b27ce18.png)

it processes OK on Windows. I will check on Linux tomorrow.

**Comment by blurpy** [comment]
> If I send
>
> `curl -v -X PUT http://localhost:9401/Settings/AudioGen/Gen2/Off/4500/-400`
>
> the server never has a chance to process it. The log output is unchanged. It looks like it's all the decision making is decided in the HttpListenerContext.

And it doesn't core dump on Windows?

> If I send
>
> `curl -d "" -v -X PUT http://localhost:9401/Settings/AudioGen/Gen2/Off/4500/-400`
>
> it processes OK on Windows.

This one processes fine on Linux, but it doesn't return the CORS headers, so it only works with curl. The browser does not let me see the response due to that.

With invalid parameters:

```
$ curl -d "" -v -X PUT http://localhost:9401/Settings/AudioGen/Gen2/Off/4500/-400
* Connected to localhost (::1) port 9401 (#0)
> PUT /Settings/AudioGen/Gen2/Off/4500/-400 HTTP/1.1
> Host: localhost:9401
> User-Agent: curl/7.73.0
> Accept: */*
> Content-Length: 0
> Content-Type: application/x-www-form-urlencoded
> 
< HTTP/1.1 400 Bad Request: Exception: (Specified argument was out of the range of valid values. (Parameter 'Amplitude must be >= -120 and <= 5.8'))
< Server: Microsoft-NetCore/2.0
< Date: Wed, 09 Dec 2020 17:58:56 GMT
< Connection: close
< Transfer-Encoding: chunked
```

With valid parameters:

```
$ curl -d "" -v -X PUT http://localhost:9401/Settings/AudioGen/Gen2/Off/4500/-40
* Connected to localhost (::1) port 9401 (#0)
> PUT /Settings/AudioGen/Gen2/Off/4500/-40 HTTP/1.1
> Host: localhost:9401
> User-Agent: curl/7.73.0
> Accept: */*
> Content-Length: 0
> Content-Type: application/x-www-form-urlencoded
> 
< HTTP/1.1 200 OK
< Access-Control-Allow-Origin: *
< Content-Type: application/json
< Server: Microsoft-NetCore/2.0
< Date: Wed, 09 Dec 2020 17:59:13 GMT
< Content-Length: 19
```

As you can see, `Access-Control-Allow-Origin: *` is missing when I get status 400.

> I will check on Linux tomorrow.

Thanks!

**Comment by blurpy** [comment]
Just wondering if you've had some time to look into the missing CORS headers on non-200 responses?

**Comment by QuantAsylum** [comment]
Hi @blurpy, I don't think this can be easily changed at this point. You can determine the limits of the various commands using CURL, and then you can code those into your app to ensure they aren't exceeded. But for the 2.0 release of the gui app, this can for sure be addressed

**Comment by blurpy** [comment]
OK, thanks for the feedback. I do have html validation of the values, which is good enough in most cases.
